apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nodejs-app-a  
  annotations:
    ngix.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nodejs-app-a
  rules:
  - host: mykube.test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-web-service
            port:
              number: 80 
