name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images         
    - name: pull image
      run: |
        docker pull devopshint/node-app:latest
     #   docker pull registry.k8s.io/e2e-test-images/agnhost:2.39
     #   kubectl create deployment hello-minikube1 --image=kicbase/echo-server:1.0
    # - name: Minikube tunnel
    #  run: | 
    #    minikube tunnel
    - name: Deploy to minikube
      run: |  
        minikube addons enable ingress
        kubectl apply -f k8s-node-app.yaml
        # kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080
    - name: Sleep for 300 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '300s'
    - name: Test service URLs
      run: |
          kubectl get svc
          kubectl get pods -A
          kubectl apply -f ingress.yaml
          kubectl get ingress
          minikube service list
          # minikube service nodejs-app --url
          #echo $(minikube service nodejs-app --url)
          curl localhost:8080
